package com.puzzle15.test;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.puzzle15.board.Puzzle15Board;
import com.puzzle15.board.Tile;
import org.junit.Before;
import org.junit.Test;

import static com.puzzle15.board.Tile.*;
import static org.assertj.core.api.Assertions.assertThat;

public class Puzzle15BoardTest {
    private final Tile EMPTY_TILE = TILE_16;
    private Puzzle15Board board = new Puzzle15Board();

    @Before
    public void setup(){
        board.reset();
    }

	@Test 
    public void testCreateNewBoard() {
	    assertThat(board.numOfMisplacedTiles()).isEqualTo(0);
    }

    @Test
    public void testMoveTile(){
        board.moveTile(TILE_15);
        assertThat(board.getTile(3, 3)).isEqualTo(TILE_15);
        assertThat(board.getTile(3, 2)).isEqualTo(EMPTY_TILE);
        board.moveTile(TILE_11);
        assertThat(board.getTile(2, 2)).isEqualTo(EMPTY_TILE);
        assertThat(board.getTile(3, 2)).isEqualTo(TILE_11);

        assertThat(board.numOfMisplacedTiles()).isEqualTo(3);
    }

    @Test
    public void testTryToMoveEmptyTile(){
        boolean success = board.moveTile(EMPTY_TILE);
        assertThat(success).isEqualTo(false);
    }

    @Test
    public void testShuffle1(){
        board.shuffle(1);
        assertThat(board.numOfMisplacedTiles()).isEqualTo(2);  //1 tile + the empty tile
    }

    @Test
    public void testShuffle2(){
        board.shuffle(2);
        assertThat(board.numOfMisplacedTiles()).isEqualTo(3);  //2 tiles + the empty tile
    }
}
